# Upstream changes from _extends are only recognized when modifications are made to this file in the default branch.
_extends: .github
repository:
  name: aws-eks-idp-roles
  description: "This component installs the `idp-roles` for EKS clusters"
  homepage: https://cloudposse.com/accelerate
  topics: terraform, terraform-component





