apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: "{{ .Values.poweruser_cluster_role }}-extra"
  labels:
    rbac.authorization.k8s.io/aggregate-to-poweruser: "true"
rules:
  - apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
    verbs:
      - list
      - get
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - storage.k8s.io
    resources:
      - storageclasses
    verbs:
      - list
      - get
      - create
      - update
      - patch
      - delete
  - apiGroups: [""]
    resources:
      - configmaps
      - persistentvolumeclaims
      - persistentvolumes
      - pods
      - pods/exec
      - pods/log
      - services
      - secrets
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups: ["apps"]
    resources:
      - deployments
      - daemonsets
      - statefulsets
      - replicasets
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups: ["batch"]
    resources:
      - jobs
      - cronjobs
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups: ["networking.k8s.io"]
    resources:
      - networkpolicies
      - ingresses
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups: ["extensions"]
    resources:
      - ingresses
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups: ["*"]
    resources:
      - events
      - endpoints
    verbs:
      - get
      - list
      - watch
  - apiGroups: ["*"]
    resources:
      - gateways
      - gatewayclasses
      - httproutes
      - tcproutes
      - tlsroutes
      - udproutes
      - referencegrants
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch